#!/bin/bash

docker run -it --rm -p 2222:2222\
        -e IDENT=6943260b4acf4259affa1fdd8dfc2efc \
        -e NAME=通用ssh蜜罐 \
        -e DESCRIBE=测完这波就歇逼 \
        -e HONEYPOT_HOST=192.168.140.171 \
        -e HONEYPOT_PORT=2222 \
        -e RABBIT_HOST=192.168.140.148 \
        -e RABBIT_PORT=5672 \
        -e RABBIT_USERNAME=guest \
        -e RABBIT_PASSWORD=guest \
        -e SERVER_HOST=192.168.140.148 \
        -e SERVER_PORT=80 \
        cowriex:2.0.0