#!/bin/bash

docker run -it --rm -p 2222:2222\
        -e IDENT=76bfa625032e46aba1d1b9e6d450fc26 \
        -e NAME=测试节点 \
        -e DESCRIBE=加的一批 \
        -e HONEYPOT_HOST=192.168.140.171 \
        -e HONEYPOT_PORT=2222 \
        -e RABBIT_HOST=192.168.140.148 \
        -e RABBIT_PORT=5672 \
        -e RABBIT_USERNAME=guest \
        -e RABBIT_PASSWORD=guest \
        -e SERVER_HOST=192.168.140.148 \
        -e SERVER_PORT=80 \
        cowriex:2.0.0